/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MM2;

import java.awt.Color;
import java.util.Random;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.time.DurationFormatUtils;
import org.apache.commons.lang3.time.StopWatch;


/**
 *
 * @author Francisco A. Reyes
 */
public class MM2 extends javax.swing.JFrame {

    static final Logger LOGGER = Logger.getLogger("MM2.MM2");

    StopWatch crono = new StopWatch();

    short cifraMax;
    String pass;
    int carac;
    String strContra = "";
    Random passCarac = new Random();

    int intentosMax;
    int restaIntentos;
    short nIntentos;
    int nivel;

    int bien1 = 0;
    int mal1 = 0;
    int fallo1 = 0;

    short pulsados = 0;

    int seleccion2;

    DurationFormatUtils formatoTiempo = new DurationFormatUtils();

    int puntos;

    /**
     * Creates new form MM2
     */
    public MM2() {
        initComponents();
        contraseña.setVisible(false);
        texto1.setEditable(false);
        listaComb.setEditable(false);

        String[] options = {"Fácil (3 cifras)", "Normal (4 cifras)", "Difícil (5 cifras)"};
        int seleccion = JOptionPane.showOptionDialog(null, "Bienvenido, elige dificultad", "MASTERMIND", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[1]);

        switch (seleccion) {
            case 0:
                nivel = 3;
                puntos = 330;
                mostrarPass.setText("***");

                btn5.setVisible(false);
                btn6.setVisible(false);
                btn7.setVisible(false);
                btn8.setVisible(false);
                btn9.setVisible(false);
                cifraMax = 4;
                intentosMax = 10;
                break;
            case 1:
                nivel = 4;
                puntos = 520;
                mostrarPass.setText("****");
                btn5.setVisible(true);
                btn6.setVisible(true);
                btn7.setVisible(true);
                btn8.setVisible(true);
                btn9.setVisible(true);

                intentosMax = 12;
                cifraMax = 9;
                break;
            case 2:
                nivel = 5;
                puntos = 650;
                mostrarPass.setText("*****");
                btn5.setVisible(true);
                btn6.setVisible(true);
                btn7.setVisible(true);
                btn8.setVisible(true);
                btn9.setVisible(true);

                intentosMax = 12;
                cifraMax = 9;
                break;
            case -1:
                System.exit(0);
                break;
        }
        System.out.println(puntos);
        crono.start();

        restaIntentos = intentosMax;

        contraseña.setVisible(false);

        for (int num = 0; num < nivel; num++) {

            pass = String.valueOf(passCarac.nextInt(cifraMax));

            if (strContra.contains(pass)) {
                num--;
            } else {
                strContra = strContra + pass;
            }
            contraseña.setText(strContra);
        }
        System.out.println(strContra);

        mostrarPass.setBackground(Color.gray);
        mostrarPass.setEditable(false);

        resultadoComprobar1.setText("Nº intentos: " + restaIntentos-- + "\n Puntos: " + puntos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        panel1 = new javax.swing.JPanel();
        comprobar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto1 = new javax.swing.JTextArea();
        borrar = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        contraseña = new javax.swing.JTextArea();
        resultadoComprobar1 = new javax.swing.JLabel();
        reiniciar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaComb = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cambiarNivel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mostrarPass = new javax.swing.JTextField();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        comprobar1.setText("Comprobar");
        comprobar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobar1ActionPerformed(evt);
            }
        });

        texto1.setEditable(false);
        texto1.setColumns(20);
        texto1.setLineWrap(true);
        texto1.setRows(5);
        texto1.setAutoscrolls(false);
        jScrollPane1.setViewportView(texto1);

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comprobar1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comprobar1)
                            .addComponent(borrar))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        scroll.setHorizontalScrollBar(null);

        contraseña.setEditable(false);
        contraseña.setColumns(20);
        contraseña.setRows(5);
        contraseña.setAutoscrolls(false);
        scroll.setViewportView(contraseña);

        reiniciar.setText("Reiniciar Partida");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn0.setText("0");
        btn0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn1.setText("1");
        btn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn4.setPreferredSize(new java.awt.Dimension(30, 30));
        btn4.setSelected(true);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn5.setMinimumSize(new java.awt.Dimension(30, 30));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        listaComb.setColumns(20);
        listaComb.setLineWrap(true);
        listaComb.setRows(5);
        jScrollPane2.setViewportView(listaComb);

        jLabel1.setText("Lista de combinaciones");

        cambiarNivel.setText("Cambiar Nivel");
        cambiarNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarNivelActionPerformed(evt);
            }
        });

        mostrarPass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mostrarPass)
                        .addGap(18, 18, 18)
                        .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(cambiarNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(resultadoComprobar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reiniciar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(reiniciar)
                        .addComponent(cambiarNivel))
                    .addComponent(mostrarPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultadoComprobar1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprobar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobar1ActionPerformed

        if (nIntentos >= intentosMax) {
            crono.stop();
            texto1.setEditable(false);
            texto1.setBackground(Color.red);
            comprobar1.setEnabled(false);
            borrar.setEnabled(false);
            mostrarPass.setText(strContra);
            int opcionJPanel = JOptionPane.showConfirmDialog(this, "¿Reiniciar?", "Has fracasado", 2);
            if (opcionJPanel == JOptionPane.OK_OPTION) {
                reiniciar.doClick();
            } else {
                if (opcionJPanel == JOptionPane.CANCEL_OPTION || opcionJPanel == JOptionPane.CLOSED_OPTION) {

                }
            }

        } else {

            String combi1 = texto1.getText();
            if (combi1.equals(contraseña.getText())) {
                crono.stop();
                contraseña.setVisible(true);
                
                comprobar1.setEnabled(false);               

                texto1.setBackground(Color.green);
                if (crono.getTime() < 60000) {
                    puntos += 100;
                } else {
                    if (crono.getTime() < 120000) {
                        puntos += 75;
                    } else {
                        if (crono.getTime() < 180000) {
                            puntos += 50;
                        } else {
                            if (crono.getTime() < 300000) {
                                puntos += 40;
                            } else {
                                if (crono.getTime() < 600000) {
                                    puntos += 20;
                                }
                            }
                        }
                    }
                }

                JOptionPane.showMessageDialog(this, "Enhorabuena, has acertado\nHas tardado: "
                        + DurationFormatUtils.formatDuration(crono.getTime(), "mm:ss") + " minutos\n Puntuación: " + puntos);
                
                mostrarPass.setText(strContra);
                btn0.setEnabled(false);
                btn1.setEnabled(false);
                btn2.setEnabled(false);
                btn3.setEnabled(false);
                btn4.setEnabled(false);
                btn5.setEnabled(false);
                btn6.setEnabled(false);
                btn7.setEnabled(false);
                btn8.setEnabled(false);
                btn9.setEnabled(false);
                borrar.setEnabled(false);

            } else {
                try {
                    switch (nivel) {
                        case 3:
                            puntos -= 30;
                            break;
                        case 4:
                            puntos -= 40;
                            break;
                        case 5:
                            puntos -= 50;
                    }
                    for (carac = 0; carac < nivel; carac++) {
                        if (combi1.charAt(carac) == strContra.charAt(carac)) {
                            bien1++;
                        } else {
                            String ccarac = String.valueOf(combi1.charAt(carac));
                            if (strContra.contains(ccarac)) {
                                mal1++;
                            } else {
                                fallo1++;
                            }
                        }
                    }
                    texto1.setText("");
                    listaComb.append(combi1 + " - " + "Bien: " + bien1 + " " + "Mal: " + mal1 + " " + "Fallo: " + fallo1 + "\n");
                } catch (StringIndexOutOfBoundsException e1) {
                    LOGGER.warning("El usuario no ha introducido las cifras necesarias");
                    JOptionPane.showMessageDialog(this, "Te faltan cifras para poder comprobar", "Atención", JOptionPane.WARNING_MESSAGE);
                    borrar.doClick();
                    listaComb.append("Intento Fallido\n");
                }

            }

            resultadoComprobar1.setText("Nº intentos: " + restaIntentos-- + "\n Puntos: " + puntos);
            nIntentos++;
            bien1 = 0;
            mal1 = 0;
            fallo1 = 0;

            pulsados = 0;

            borrar.setEnabled(true);
            btn0.setEnabled(true);
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
        }
    }//GEN-LAST:event_comprobar1ActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed

        texto1.setText("");

        pulsados = 0;

        btn0.setEnabled(true);
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);

    }//GEN-LAST:event_borrarActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        int opcionJPanel2 = JOptionPane.showConfirmDialog(this, "¿Estás seguro?", "La partida se reiniciará", 2);
        if (opcionJPanel2 == JOptionPane.OK_OPTION) {

            nIntentos = 0;
            intentosMax = 10;
            strContra = "";
            for (int num = 0; num < nivel; num++) {

                pass = String.valueOf(passCarac.nextInt(9));

                if (strContra.contains(pass)) {
                    num--;
                } else {
                    strContra = strContra + pass;
                }
                contraseña.setText(strContra);
                System.out.println(strContra);
            }

            contraseña.setVisible(false);

            comprobar1.setEnabled(true);

            texto1.setEditable(true);
            texto1.setText("");
            texto1.setBackground(Color.WHITE);
            listaComb.setText("");

            if (crono.isStopped() == true) {
                crono.reset();
                crono.start();
            } else {
                crono.stop();
                crono.reset();
                crono.start();
            }

            pulsados = 0;

            btn0.setEnabled(true);
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);

            switch (nivel) {
                case 3:
                    puntos = 330;
                    mostrarPass.setText("***");

                    btn5.setVisible(false);
                    btn6.setVisible(false);
                    btn7.setVisible(false);
                    btn8.setVisible(false);
                    btn9.setVisible(false);
                    cifraMax = 4;
                    restaIntentos = 10;
                    break;
                case 4:
                    puntos = 520;
                    mostrarPass.setText("****");

                    btn5.setVisible(true);
                    btn6.setVisible(true);
                    btn7.setVisible(true);
                    btn8.setVisible(true);
                    btn9.setVisible(true);

                    intentosMax = 12;
                    restaIntentos = intentosMax;
                    cifraMax = 9;
                    break;
                case 5:
                    puntos = 650;
                    mostrarPass.setText("*****");

                    btn5.setVisible(true);
                    btn6.setVisible(true);
                    btn7.setVisible(true);
                    btn8.setVisible(true);
                    btn9.setVisible(true);

                    intentosMax = 12;
                    restaIntentos = intentosMax;
                    cifraMax = 9;
                    break;
            }

            resultadoComprobar1.setText("Nº intentos: " + restaIntentos-- + "\n Puntos: " + puntos);
        } else {
            if (opcionJPanel2 == JOptionPane.CANCEL_OPTION) {

            }
        }

    }//GEN-LAST:event_reiniciarActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        texto1.append("0");
        btn0.setEnabled(false);
        pulsados++;

        if (pulsados >= nivel) {
            btn0.setEnabled(false);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        texto1.append("1");
        btn1.setEnabled(false);

        pulsados++;

        if (pulsados >= nivel) {
            btn0.setEnabled(false);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        texto1.append("2");
        btn2.setEnabled(false);

        pulsados++;

        if (pulsados >= nivel) {
            btn0.setEnabled(false);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        texto1.append("3");
        btn3.setEnabled(false);
        pulsados++;

        if (pulsados >= nivel) {
            btn0.setEnabled(false);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        texto1.append("4");
        btn4.setEnabled(false);
        pulsados++;

        if (pulsados >= nivel) {
            btn0.setEnabled(false);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        texto1.append("5");
        btn5.setEnabled(false);
        pulsados++;

        if (pulsados >= nivel) {
            btn0.setEnabled(false);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        texto1.append("6");
        btn6.setEnabled(false);
        pulsados++;

        if (pulsados >= nivel) {
            btn0.setEnabled(false);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        texto1.append("7");
        btn7.setEnabled(false);
        pulsados++;

        if (pulsados >= nivel) {
            btn0.setEnabled(false);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        texto1.append("8");
        btn8.setEnabled(false);
        pulsados++;

        if (pulsados >= nivel) {
            btn0.setEnabled(false);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        texto1.append("9");
        btn9.setEnabled(false);
        pulsados++;

        if (pulsados >= nivel) {
            btn0.setEnabled(false);
            btn1.setEnabled(false);
            btn2.setEnabled(false);
            btn3.setEnabled(false);
            btn4.setEnabled(false);
            btn5.setEnabled(false);
            btn6.setEnabled(false);
            btn7.setEnabled(false);
            btn8.setEnabled(false);
            btn9.setEnabled(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void cambiarNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarNivelActionPerformed

        int opcionJPanel = JOptionPane.showConfirmDialog(this, "Vas a cambiar de nivel\nLa partida se reiniciara", "Selección de nivel", 2);
        if (opcionJPanel == JOptionPane.OK_OPTION) {

            String[] options2 = {"Fácil (3 cifras)", "Normal (4 cifras)", "Difícil (5 cifras)"};
            seleccion2 = JOptionPane.showOptionDialog(null, "Elige nivel", "Selección de nivel", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options2, options2[1]);
            switch (seleccion2) {
                case 0:
                    nivel = 3;
                    puntos = 330;

                    btn5.setVisible(false);
                    btn6.setVisible(false);
                    btn7.setVisible(false);
                    btn8.setVisible(false);
                    btn9.setVisible(false);
                    cifraMax = 4;
                    intentosMax = 10;
                    break;
                case 1:
                    nivel = 4;
                    puntos = 520;
                    btn5.setVisible(true);
                    btn6.setVisible(true);
                    btn7.setVisible(true);
                    btn8.setVisible(true);
                    btn9.setVisible(true);

                    intentosMax = 12;
                    cifraMax = 9;
                    break;
                case 2:
                    nivel = 5;
                    puntos = 650;

                    btn5.setVisible(true);
                    btn6.setVisible(true);
                    btn7.setVisible(true);
                    btn8.setVisible(true);
                    btn9.setVisible(true);

                    intentosMax = 12;
                    cifraMax = 9;
                    break;
            }

        } else {
            if (opcionJPanel == JOptionPane.CANCEL_OPTION) {

            } else {
                if (opcionJPanel == JOptionPane.CLOSED_OPTION) {

                }
            }
        }
        nIntentos = 0;

        strContra = "";
        for (int num = 0; num < nivel; num++) {

            pass = String.valueOf(passCarac.nextInt(cifraMax));

            if (strContra.contains(pass)) {
                num--;
            } else {
                strContra = strContra + pass;
            }
            contraseña.setText(strContra);
            System.out.println(strContra);
        }

        contraseña.setVisible(false);

        comprobar1.setEnabled(true);

        texto1.setEditable(true);
        texto1.setText("");
        texto1.setBackground(Color.WHITE);
        listaComb.setText("");

        if (crono.isStopped() == true) {
            crono.reset();
            crono.start();
        } else {
            crono.stop();
            crono.reset();
            crono.start();
        }

        pulsados = 0;

        btn0.setEnabled(true);
        btn1.setEnabled(true);
        btn2.setEnabled(true);
        btn3.setEnabled(true);
        btn4.setEnabled(true);
        btn5.setEnabled(true);
        btn6.setEnabled(true);
        btn7.setEnabled(true);
        btn8.setEnabled(true);
        btn9.setEnabled(true);

        switch (nivel) {
            case 3:
                puntos = 330;
                mostrarPass.setText("***");

                btn5.setVisible(false);
                btn6.setVisible(false);
                btn7.setVisible(false);
                btn8.setVisible(false);
                btn9.setVisible(false);
                cifraMax = 4;
                restaIntentos = 10;
                intentosMax = 10;
                break;
            case 4:
                puntos = 520;
                mostrarPass.setText("****");

                btn5.setVisible(true);
                btn6.setVisible(true);
                btn7.setVisible(true);
                btn8.setVisible(true);
                btn9.setVisible(true);

                intentosMax = 12;
                restaIntentos = intentosMax;
                cifraMax = 9;
                break;
            case 5:
                puntos = 650;
                mostrarPass.setText("*****");

                btn5.setVisible(true);
                btn6.setVisible(true);
                btn7.setVisible(true);
                btn8.setVisible(true);
                btn9.setVisible(true);

                intentosMax = 12;
                restaIntentos = intentosMax;
                cifraMax = 9;
                break;
        }

        resultadoComprobar1.setText("Nº intentos: " + restaIntentos-- + "\n Puntos: " + puntos);
        //String[] options2 = {"Fácil (3 cifras)", "Normal (4 cifras)", "Difícil (5 cifras)"};
        //int seleccion2 = JOptionPane.showOptionDialog(null, "Elige nivel", "Selección de nivel", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options2, options2[1]);

    }//GEN-LAST:event_cambiarNivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MM2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MM2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton cambiarNivel;
    private javax.swing.JButton comprobar1;
    private javax.swing.JTextArea contraseña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea listaComb;
    private javax.swing.JTextField mostrarPass;
    private javax.swing.JPanel panel1;
    private javax.swing.JButton reiniciar;
    private javax.swing.JLabel resultadoComprobar1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextArea texto1;
    // End of variables declaration//GEN-END:variables
}
